/*
 * Auto-generated fuzzing harness for: Cronet_Metrics_response_start_get
 * Library: /Users/pkorhale/Documents/project-work/SOFuzz/output/extracted/base/x86_64/libcronet.76.0.3809.111.so
 * Generated by SOFuzz
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <signal.h>
#include <setjmp.h>
#include <unistd.h>
#include <fcntl.h>
#include <dlfcn.h>
#include <sys/types.h>
#include <sys/stat.h>

#define MAX_INPUT_SIZE 1048576
#define TIMEOUT_SECONDS 2
#define SO_PATH "/Users/pkorhale/Documents/project-work/SOFuzz/output/extracted/base/x86_64/libcronet.76.0.3809.111.so"
#define FUNCTION_NAME "Cronet_Metrics_response_start_get"

static sigjmp_buf jump_buffer;
static volatile sig_atomic_t got_signal = 0;

void signal_handler(int sig) {
    got_signal = sig;
    siglongjmp(jump_buffer, 1);
}

void setup_signal_handlers(void) {
    struct sigaction sa;
    sa.sa_handler = signal_handler;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;
    
    sigaction(SIGSEGV, &sa, NULL);
    sigaction(SIGABRT, &sa, NULL);
    sigaction(SIGFPE, &sa, NULL);
    sigaction(SIGILL, &sa, NULL);
    sigaction(SIGBUS, &sa, NULL);
    sigaction(SIGALRM, &sa, NULL);
}

uint8_t* read_input_file(const char* filename, size_t* size) {
    FILE* f = fopen(filename, "rb");
    if (!f) {
        perror("fopen");
        return NULL;
    }
    
    fseek(f, 0, SEEK_END);
    long file_size = ftell(f);
    fseek(f, 0, SEEK_SET);
    
    if (file_size <= 0 || file_size > MAX_INPUT_SIZE) {
        fclose(f);
        return NULL;
    }
    
    uint8_t* buffer = (uint8_t*)malloc(file_size + 1);
    if (!buffer) {
        fclose(f);
        return NULL;
    }
    
    size_t bytes_read = fread(buffer, 1, file_size, f);
    fclose(f);
    
    buffer[file_size] = 0;
    *size = bytes_read;
    
    return buffer;
}

uint8_t* read_stdin(size_t* size) {
    uint8_t* buffer = (uint8_t*)malloc(MAX_INPUT_SIZE);
    if (!buffer) return NULL;
    
    size_t total_read = 0;
    size_t bytes_read;
    
    while ((bytes_read = fread(buffer + total_read, 1, MAX_INPUT_SIZE - total_read, stdin)) > 0) {
        total_read += bytes_read;
        if (total_read >= MAX_INPUT_SIZE) break;
    }
    
    if (total_read == 0) {
        free(buffer);
        return NULL;
    }
    
    buffer[total_read] = 0;
    *size = total_read;
    
    return buffer;
}

int main(int argc, char* argv[]) {
    uint8_t* input_data = NULL;
    size_t input_size = 0;
    void* lib_handle = NULL;
    int result = 0;
    
    setup_signal_handlers();
    alarm(TIMEOUT_SECONDS);
    
    if (argc > 1) {
        input_data = read_input_file(argv[1], &input_size);
    } else {
        input_data = read_stdin(&input_size);
    }
    
    if (!input_data || input_size == 0) {
        fprintf(stderr, "Failed to read input\n");
        return 1;
    }
    
    lib_handle = dlopen(SO_PATH, RTLD_NOW);
    if (!lib_handle) {
        fprintf(stderr, "dlopen failed: %s\n", dlerror());
        free(input_data);
        return 1;
    }
    
    dlerror();
    
    typedef void (*target_func_t)(void*, size_t);
    target_func_t target_func = (target_func_t)dlsym(lib_handle, FUNCTION_NAME);
    
    char* error = dlerror();
    if (error != NULL) {
        fprintf(stderr, "dlsym failed: %s\n", error);
        dlclose(lib_handle);
        free(input_data);
        return 1;
    }
    
    if (sigsetjmp(jump_buffer, 1) == 0) {
        target_func(input_data, input_size);
        result = 0;
    } else {
        fprintf(stderr, "CRASH: Signal %d\n", got_signal);
        result = 128 + got_signal;
    }
    
    dlclose(lib_handle);
    free(input_data);
    
    return result;
}
